"""add_frgp_data

Revision ID: 241b64b84e43
Revises: 11e53ed6b75a
Create Date: 2024-02-26 07:57:08.314468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '241b64b84e43'
down_revision = '11e53ed6b75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifact_requests', sa.Column('frgp_data', sa.Text(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    op.drop_column('artifact_requests', 'frgp_data')

    # ### end Alembic commands ###
