"""add_cart_to_persons

Revision ID: 897649b706ce
Revises: 29d8a106959c
Create Date: 2024-09-16 06:51:53.522322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '897649b706ce'
down_revision = '29d8a106959c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('persons', sa.Column('cart', sa.Text(), nullable=True))
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'cart')
    