"""add_groupingId

Revision ID: 8dbc7f681fda
Revises: 29d8a106959c
Create Date: 2024-08-29 23:55:52.261822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8dbc7f681fda'
down_revision = '29d8a106959c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('groupingId', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts', 'groupingId')
    # ### end Alembic commands ###
