"""add_phone_number

Revision ID: b855f456a919
Revises: d8dc7021a65f
Create Date: 2024-01-02 00:28:07.227042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b855f456a919'
down_revision = 'd8dc7021a65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('countryCode', sa.String(length=16), nullable=True))
    op.add_column('persons', sa.Column('mobileNumber', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'mobileNumber')
    op.drop_column('persons', 'countryCode')
    # ### end Alembic commands ###
