"""update_labels_fk

Revision ID: d1caf77fb02c
Revises: 241b64b84e43
Create Date: 2024-03-15 00:27:36.671688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1caf77fb02c'
down_revision = '241b64b84e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('labels', 'artifact_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('labels_artifact_id_fkey', 'labels', type_='foreignkey')
    op.create_foreign_key(None, 'labels', 'artifacts', ['artifact_id'], ['artifact_group_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.create_foreign_key('labels_artifact_id_fkey', 'labels', 'artifacts', ['artifact_id'], ['id'], ondelete='CASCADE')
    op.alter_column('labels', 'artifact_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artifacts', 'shortdesc',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    # ### end Alembic commands ###
