"""update_labels_fk

Revision ID: e7c5cbb0a587
Revises: 241b64b84e43
Create Date: 2024-03-15 17:46:45.805479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7c5cbb0a587'
down_revision = '241b64b84e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.create_unique_constraint(None, 'artifacts', ['artifact_group_id'])
    op.alter_column('labels', 'artifact_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('labels_artifact_id_fkey', 'labels', type_='foreignkey')
    op.create_foreign_key(None, 'labels', 'artifacts', ['artifact_id'], ['artifact_group_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.create_foreign_key('labels_artifact_id_fkey', 'labels', 'artifacts', ['artifact_id'], ['id'], ondelete='CASCADE')
    op.alter_column('labels', 'artifact_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'artifacts', type_='unique')
    
